services:
  postgres:
    image: postgres:16
    container_name: project_management_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: project_management_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5423:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: